version: 1.0.{build}

before_build:
- cmd: nuget restore CICDSample\CICDSample.sln

build:
  verbosity: minimal
  publish_azure: true
  
test_script:
- cmd: dotnet test CICDSample\src\CICDSample.Tests


